#!/bin/bash

#$ -pe smp 20
#$ -q UI
#$ -m a
#$ -M james-kent@uiowa.edu
#$ -o /Users/jdkent/bids/derivatives/code/nibetaseries/out/
#$ -e /Users/jdkent/bids/derivatives/code/nibetaseries/err/

singularity run --cleanenv /Users/jdkent/bids/derivatives/code/nibetaseries/nibetaseries-v0.6.0.simg \
    nibs -a /Users/jdkent/bids/derivatives/data/overall_response_atlas.nii.gz \
         -l /Users/jdkent/bids/derivatives/data/overall_response.tsv \
         --hrf-model "glover + derivative" \
         --estimator lss \
	 --nthreads 8 \
	 --smoothing-kernel 0.0 \
	 --high-pass 0 \
	 --space-label MNI152NLin2009cAsym \
	 --participant-label GE120024 \
	 --database-path /nfsscratch/Users/jdkent/work/Aim1nibslsa-overallresponse/dbcache \
         -c white_matter csf framewise_displacement "cosine[0-9]{1,2}" "non_steady_state_outlier[0-9]{2}" "motion_outlier[0-9]{1,3}" \
         -w /nfsscratch/Users/jdkent/work/Aim1nibslss-overallresponseAddDerivative \
	 /Users/jdkent/bids fmriprep /Users/jdkent/bids/derivatives/lss-overallresponseAddDerivative participant
