#!/bin/bash

#$ -pe smp 20
#$ -q UI,all.q
#$ -m a
#$ -M james-kent@uiowa.edu
#$ -o /Users/jdkent/bids/derivatives/code/nibetaseries/out/
#$ -e /Users/jdkent/bids/derivatives/code/nibetaseries/err/

singularity run --cleanenv /Users/jdkent/bids/derivatives/code/nibetaseries/nibetaseries-v0.4.2-gh280.simg \
    nibs -a /Users/jdkent/bids/derivatives/data/Schaefer2018_400Parcels_17Networks_order_FSLMNI152_2mm.nii.gz \
         -l /Users/jdkent/bids/derivatives/data/schaefer_parcel-400_network-17.tsv \
         --hrf-model glover \
         --estimator lsa \
	 --nthreads 8 \
	 --smoothing-kernel 0.0 \
	 --high-pass 0 \
	 --space-label MNI152NLin2009cAsym \
	 --participant-label GE120019 \
	 --database-path /nfsscratch/Users/jdkent/work/Aim1nibslsa-overallresponse/dbcache \
         -c "cosine[0-9]{1,2}" "non_steady_state_outlier[0-9]{2}" \
         -w /nfsscratch/Users/jdkent/work/Aim1nibslsa-schaeferparcel-400NoConfounds \
	 /Users/jdkent/bids fmriprep /Users/jdkent/bids/derivatives/lsa-schaeferparcel-400NoConfounds participant
