#!/bin/bash

#$ -pe smp 20
#$ -q all.q,UI
#$ -m a
#$ -M james-kent@uiowa.edu
#$ -o /Users/jdkent/bids/derivatives/code/nibetaseries/out/
#$ -e /Users/jdkent/bids/derivatives/code/nibetaseries/err/

singularity run --cleanenv /Users/jdkent/bids/derivatives/code/nibetaseries/nibetaseries-v0.6.0.simg \
    nibs --hrf-model glover \
         --estimator lsa \
	 --nthreads 8 \
	 --smoothing-kernel 0.0 \
	 --high-pass 0 \
	 --space-label MNI152NLin2009cAsym \
	 --participant-label GE120028 \
         --no-signal-scaling \
         --return-residuals \
	 --database-path /nfsscratch/Users/jdkent/work/Aim1nibslsa-overallresponse/dbcache \
         -c white_matter csf framwise_displacement "cosine[0-9]{1,2}" "non_steady_state_outlier[0-9]{2}" "motion_outlier[0-9]{1,3}" \
         -w /nfsscratch/Users/jdkent/work/lsaAim1nibsNoSignalScale \
	 /Users/jdkent/bids fmriprep /Users/jdkent/bids/derivatives/lsaNoSignalScale participant
