#!/bin/bash

#$ -pe smp 20
#$ -q UI,all.q
#$ -m a
#$ -M james-kent@uiowa.edu
#$ -o /Users/jdkent/bids/derivatives/code/nibetaseries/out/
#$ -e /Users/jdkent/bids/derivatives/code/nibetaseries/err/

singularity run --cleanenv /Users/jdkent/bids/derivatives/code/nibetaseries/nibetaseries-v0.4.2-gh280.simg \
    nibs -a /Users/jdkent/bids/derivatives/data/ATLAS_FILE \
         -l /Users/jdkent/bids/derivatives/data/LUT_TSV \
         --hrf-model glover \
         --estimator ESTIMATOR \
	 --nthreads 8 \
	 --smoothing-kernel 0.0 \
	 --high-pass 0 \
	 --space-label MNI152NLin2009cAsym \
	 --participant-label SUBJECT \
	 --database-path /nfsscratch/Users/jdkent/work/Aim1nibslsa-overallresponseblock/dbcache \
         -c white_matter csf framewise_displacement "cosine[0-9]{1,2}" "non_steady_state_outlier[0-9]{2}" "motion_outlier[0-9]{1,3}" \
         -w /nfsscratch/Users/jdkent/work/Aim1nibsESTIMATOR-DATASOURCEblock \
	 /Users/jdkent/bids fmriprep /Users/jdkent/bids/derivatives/ESTIMATOR-DATASOURCEblock participant
